# .github/workflows/dotnet.yml
name: .NET CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
      # v4 is the current major; adjust versions as you need
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore
        run: dotnet restore NxRelay.sln

      - name: Build
        run: dotnet build NxRelay.sln --configuration Release --no-restore

      - name: Test
        run: |
          dotnet test \
          -c Release \
          --no-build \
          --logger "trx;LogFileName=tests.trx" \
          --collect "XPlat Code Coverage" \
          /p:CollectCoverage=true \
          /p:CoverletOutput=TestResults/coverage/ \
          /p:CoverletOutputFormat=cobertura \
          NxRelay.Tests/NxRelay.Tests.csproj

      - name: Upload test artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: |
            **/TestResults/**/*.trx
            **/coverage.cobertura.xml
